nnsvs_root:                 nnsvs
spk:                        ExpModel
tag:                        cp6

out_dir:                    target/data

exclude_songs:              []

table_path:                 source/dic/hangul_ext.table
question_path:              source/hed/korean_question_v2.1.hed

sample_rate:                44100

stage0:
    db_root:                source/singing_database
    lang_mode:              kor

    ### How to segment LAB and WAV before training
    # Changing this config might help you avoid "SegmentationFault" on stage 1.
    # Choices are [null, long, middle, short] (middle is recommended)
    # If "long",   LAB is devided at "pau"-"pau" or "pau""-"sil phoneme pattern.
    # If "middle", LAB is devided at the start of each <middle_frequency> "pau"s.
    # If "short",  LAB is devided at the start of each "pau" phoneme.
    segmentation_mode:      middle
    middle_frequency:       2

    # Choices are [strict, middle, lenient]
    vowel_duration_check:   middle

# stage 1
timelag_features:           defaults
duration_features:          defaults
acoustic_features:          static_deltadelta

trajectory_smoothing: false
trajectory_smoothing_cutoff: 50

# test arguments for proper f0 range
# f0_floor: 150
# f0_ceil: 700

# test argument for correct VUV
correct_vuv: false

# test argument for relative_f0
relative_f0: false


# stage 4
# symlink during training in notebook.
acoustic_model:             acoustic_custom
acoustic_train:             myconfig
acoustic_data:              myconfig

duration_model:             duration_custom
duration_train:             myconfig
duration_data:              myconfig

timelag_model:              timelag_custom
timelag_train:              myconfig
timelag_data:               myconfig

# postfilter stuff
postfilter_model:           postfilter_merged
postfilter_train:           mgc
postfilter_data:            myconfig

pretrained_expdir:

# stage 6
timelag_synthesis:          defaults
duration_synthesis:         defaults
acoustic_synthesis:         defaults

# latest.pth or best.pth are recommended
timelag_eval_checkpoint:    best_loss.pth
duration_eval_checkpoint:   best_loss.pth
acoustic_eval_checkpoint:   latest.pth

# # vocoder stuff (stage 8)
vocoder_model: hn-sinc-nsf_sr44k_pwgD
pretrained_vocoder_checkpoint:
vocoder_eval_checkpoint:
